version: '3'

services:
  app:
    container_name: executor-service
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports: 
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
    volumes:
      - logs:/app/logs
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
   
  postgres:
    container_name: postgres
    image: postgres:14
    env_file: .env
    ports:
      - 5433:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    container_name: redis
    image: redis:7.2
    env_file: .env
    ports:
      - 6380:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pg_data:
  logs:
