server:
  # port: "8080"
  # путь до папки с логами
  logPath: ./logs/

postgres:
  # количество подключений к базе
  maxConnPoolSize: 5

redis:
  # время жизни в секундах
  pidTTL: 1800

general:
  # путь до стандарной оболочки
  defaultShellPath: /bin/sh
